print("Cual es tu nombre ?\t")
nombre = input()
print("Cual es tu edad ?\t")
edad = input()
print("Cual es tu altura ?\t")
altura = input()
print("Cual es tu RH ?\t")
sangre = input()

print("Hola ", nombre, "!")
print("Tienes ", edad, "años")
print("Con altura de: ", altura, "cm")
print("Y de RH: ", sangre)